// src/app/common/PageContent.vue
<template>
    <article v-if="content" class="page-content">
        <h1 class="title">{{content.title}}</h1>
        <div class="cms-content" v-html="content.content"></div>
    </article>
</template>

<script lang="ts">
    import Vue from 'vue';
    import {Component, Prop} from 'vue-property-decorator';

    import {PageContent} from '@app/store/models/PageContent';

    @Component({
        name: 'CubPageContent'
    })
    export default class CubPageContent extends Vue {
        @Prop() public content: PageContent;
    }
</script>

// src/app/shared/page-content/page-content.component.ts
import {Component, Input, ChangeDetectionStrategy, OnChanges} from '@angular/core';

import {PageContent} from '@app/core/models/PageContent';
import {RouteData} from '@app/core/interfaces/RouteData';

@Component({
    selector: 'app-page-content',
    templateUrl: 'page-content.component.html',
    styleUrls: ['page-content.component.scss'],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class PageContentComponent implements OnChanges {

    @Input() public data: RouteData;
    public content: PageContent;

    public ngOnChanges(): void {
        if (this.data && this.data.content) {
            this.content = this.data.content;
        }
    }
}

<article *ngIf="content">
    <h1 class="title">{{content.title}}</h1>
    <div class="cms-content" [innerHtml]="content.content | markdown"></div>
</article>
