// src/app/home/news-feed/NewsFeed.vue
<template>
    <div class="news-feed">
        <h2>News and Updates</h2>
        <cub-news-item v-for="post in posts" :key="post.id" v-bind:post="post"></cub-news-item>
        <p v-if="!posts || posts.length === 0" class="text-muted">No recent news.</p>
    </div>
</template>

<script lang="ts">
    import Vue from 'vue';
    import {Component, Prop} from 'vue-property-decorator';

    import {FbPost} from '@app/store/models/FbPost';
    import CubNewsItem from '@app/home/news-feed/NewsItem.vue';

    @Component({
        components: {CubNewsItem}
    })
    export default class CubNewsFeedList extends Vue {
        @Prop() public posts: FbPost[];
    }
</script>

// src/app/home/news-feed/news-feed.component.ts
import {Component, Input, ChangeDetectionStrategy} from '@angular/core';

import {FbPost} from '@app/core/models/FbPost';

@Component({
    selector: 'app-news-feed',
    templateUrl: 'news-feed.component.html',
    styleUrls: ['news-feed.component.scss'],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class NewsFeedComponent {
    @Input() public posts: FbPost[];
}

<h2>News and Updates</h2>
<ng-container *ngIf="posts && posts.length > 0; else none">
    <app-fb-post *ngFor="let post of posts" [post]="post"></app-fb-post>
</ng-container>
<ng-template #none>
    <p class="text-muted">No recent news.</p>
</ng-template>
